version: 6.0.8.{build}
clone_depth: 100

image:
  - Visual Studio 2015

environment:
  PYTHON: "C:\\Python27-x64"
  PYTHON_VERSION: "2.7.11"
  PYTHON_ARCH: "64"
  CONAN_USER_HOME: "C:\\projects\\deps\\conan"

platform:
  - x64

configuration:
  - Release

cache:
  - C:\projects\deps\conan

install:
  - mkdir C:\projects\deps
  - mkdir C:\projects\deps\conan
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - C:\Python27-x64\Scripts\pip.exe install conan

before_build:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo -> %APPVEYOR_BUILD_FOLDER%

build_script:
  - mkdir build & cd build
  - conan install ..
  - cmake .. -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=%configuration%
  - cmake --build . --config %configuration%

test_script:
  - cmake --build . --config %configuration% --target tests
  - cmake --build . --config %configuration% --target ctest
